//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructoraUdcModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_User
    {
        public SEC_User()
        {
            this.SEC_Session = new HashSet<SEC_Session>();
            this.SEC_User_role = new HashSet<SEC_User_role>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public string document { get; set; }
        public string email { get; set; }
        public string password_user { get; set; }
        public string phone { get; set; }
        public int city_id { get; set; }
        public bool removed { get; set; }
        public Nullable<System.DateTime> removed_date { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.DateTime> ipdate_date { get; set; }
        public Nullable<int> removed_user_id { get; set; }
        public Nullable<int> create_user_id { get; set; }
        public Nullable<int> update_user_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual PMT_City PMT_City { get; set; }
        public virtual ICollection<SEC_Session> SEC_Session { get; set; }
        public virtual ICollection<SEC_User_role> SEC_User_role { get; set; }
    }
}
