//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructoraUdcModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_Session
    {
        public long id { get; set; }
        public int user_id { get; set; }
        public System.DateTime login_date { get; set; }
        public string ip_address { get; set; }
        public string token { get; set; }
        public bool token_status { get; set; }
        public Nullable<System.DateTime> logout_date { get; set; }
    
        public virtual SEC_User SEC_User { get; set; }
    }
}
