//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructoraUdcModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_Role
    {
        public SEC_Role()
        {
            this.SEC_User_role = new HashSet<SEC_User_role>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool removed { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<SEC_User_role> SEC_User_role { get; set; }
    }
}
